#ifndef SHARED_SYSCALL_H
#define SHARED_SYSCALL_H

#include <stdint.h>
#include "syscall/cpu.h"
#include "syscall/thread.h"

typedef enum syscall
{
    SYSCALL_CPU_GET_SYSTIME,
    SYSCALL_CPU_GET_CORES,
    SYSCALL_CPU_GET_FREQ,
    SYSCALL_THREAD_GET_PID,
    SYSCALL_THREAD_GET_TID,
    SYSCALL_THREAD_GET_SCHED,
    SYSCALL_THREAD_SET_SCHED,
    SYSCALL_THREAD_GET_CPU_TICKS,
    SYSCALL_THREAD_SLEEP,
    SYSCALL_THREAD_YIELD_THREAD,
    SYSCALL_THREAD_YIELD_BUDGET,
    SYSCALL_THREAD_YIELD_PERIOD
} syscall_t;

#endif