#ifndef RESET_H
#define RESET_H

#include "common.h"

#define RESET_REG_BASE 0x40020000
#define RESET_REG_RESET REG((RESET_REG_BASE + 0x00))
#define RESET_REG_RESET_DONE REG((RESET_REG_BASE + 0x08))

typedef enum reset_subsys {
    RESET_SUBSYS_ADC = 0,
    RESET_SUBSYS_BUSCTRL = 1,
    RESET_SUBSYS_DMA = 2,
    RESET_SUBSYS_HSTX = 3,
    RESET_SUBSYS_I2C0 = 4,
    RESET_SUBSYS_I2C1 = 5,
    RESET_SUBSYS_IOBANK0 = 6,
    RESET_SUBSYS_IOQSPI = 7,
    RESET_SUBSYS_JTAG = 8,
    RESET_SUBSYS_PADS_BANK0 = 9,
    RESET_SUBSYS_PADS_QSPI = 10,
    RESET_SUBSYS_PIO0 = 11,
    RESET_SUBSYS_PIO1 = 12,
    RESET_SUBSYS_PIO2 = 13,
    RESET_SUBSYS_PLL_SYS = 14,
    RESET_SUBSYS_PLL_USB = 15,
    RESET_SUBSYS_PWM = 16,
    RESET_SUBSYS_SHA256 = 17,
    RESET_SUBSYS_SPI0 = 18,
    RESET_SUBSYS_SPI1 = 19,
    RESET_SUBSYS_SYSCFG = 20,
    RESET_SUBSYS_SYSINFO = 21,
    RESET_SUBSYS_TBMAN = 22,
    RESET_SUBSYS_TIMER0 = 23,
    RESET_SUBSYS_TIMER1 = 24,
    RESET_SUBSYS_TRNG = 25,
    RESET_SUBSYS_UART0 = 26,
    RESET_SUBSYS_UART1 = 27,
    RESET_SUBSYS_USBCTRL = 28
} reset_subsys_t;

bool reset_subsys(reset_subsys_t subsys);

#endif